# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

# Trigger the workflow on push events to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Run on a standard Linux machine in the cloud

    steps:
    # Step 1: Check out your repository's code
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Set up a Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Step 3: Install the project dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run your unit tests
    # The entire pipeline will fail if any test does not pass
    - name: Run Pytest
      run: |
        pytest

    # Step 5: Log in to Docker Hub using the secure secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 6: Build the Docker image and push it to your Docker Hub repository
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/scalable-ml-service:latest